### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by pshahnazari** [lauzikaite/massflowR#6]
Dear lauzikaite,
I wonder if you help me to install package I used install.packages("remotes")
remotes::install_github("lauzikaite/massflowR"), and wrote unpacked but it wasn't in my library .
Could you please add massFlowR.zip in your github that I can download and install locally.
Thank you

**Comment by lauzikaite** [comment]
Hi!
I'd try and install using the following function, which I've tested on multiple OS and R environments

```
# To install dependencies
install_dependencies <- function () {
  dependencies <- c("xcms",  "MSnbase", "faahKO", "igraph", "doParallel",  "foreach", "ggplot2", "viridis", "gridExtra")
  installed <- installed.packages()
  to_install <- subset(dependencies, !(dependencies %in% installed[, "Package"]))
  if (length(to_install) != 0) {
    if (!requireNamespace("BiocManager", quietly = TRUE)) {
      install.packages("BiocManager")
    }
    message("Installing packages: ", to_install, " ...")
    BiocManager::install(to_install)
  } else {
    message("All dependencies are already installed.")
  }
}
install_dependencies()

# To install development version
devtools::install_github("lauzikaite/massflowR", dependencies = FALSE)
```

Let me know if you encounter issues while installing it in this way.

Thanks,
Elze

**Comment by pshahnazari** [comment]
Hi Elze,
I could not install  and I found this error
> install_dependencies <- function () {
+   dependencies <- c("xcms",  "MSnbase", "faahKO", "igraph", "doParallel",  "foreach", "ggplot2", "viridis", "gridExtra")
+   installed <- installed.packages()
+   to_install <- subset(dependencies, !(dependencies %in% installed[, "Package"]))
+   if (length(to_install) != 0) {
+     if (!requireNamespace("BiocManager", quietly = TRUE)) {
+       install.packages("BiocManager")
+     }
+     message("Installing packages: ", to_install, " ...")
+     BiocManager::install(to_install)
+   } else {
+     message("All dependencies are already installed.")
+   }
+ }
> install_dependencies()
All dependencies are already installed.
> # To install dependencies
> install_dependencies <- function () {
+   dependencies <- c("xcms",  "MSnbase", "faahKO", "igraph", "doParallel",  "foreach", "ggplot2", "viridis", "gridExtra")
+   installed <- installed.packages()
+   to_install <- subset(dependencies, !(dependencies %in% installed[, "massFlowR"]))
+   if (length(to_install) != 0) {
+     if (!requireNamespace("BiocManager", quietly = TRUE)) {
+       install.packages("BiocManager")
+     }
+     message("Installing packages: ", to_install, " ...")
+     BiocManager::install(to_install)
+   } else {
+     message("All dependencies are already installed.")
+   }
+ }
> # To install dependencies
> install_dependencies <- function () {
+   dependencies <- c("xcms",  "MSnbase", "faahKO", "igraph", "doParallel",  "foreach", "ggplot2", "viridis", "gridExtra")
+   installed <- installed.packages(massFlowR)
+   to_install <- subset(dependencies, !(dependencies %in% installed[, "massFlowR"]))
+   if (length(to_install) != 0) {
+     if (!requireNamespace("BiocManager", quietly = TRUE)) {
+       install.packages("BiocManager")
+     }
+     message("Installing packages: ", to_install, "massFlowR")
+     BiocManager::install(to_install)
+   } else {
+     message("All dependencies are already installed.")
+   }
+ }
> install_dependencies()
Error in installed.packages(massFlowR) : object 'massFlowR' not found
Could you help me to install and run your package. Actually I am eager to use your package .
Thanks 
Parisa

**Comment by lauzikaite** [comment]
There is an error in your code. Could you please copy and paste the code that I shared in my previous message exactly as it is and run it?

**Comment by pshahnazari** [comment]
sure, my codes: if (!requireNamespace("BiocManager", quietly = TRUE))
      install.packages("BiocManager")
    BiocManager::install(" massFlowR")
The downloaded source packages are in
	‘C:\Users\Win 1809 UEFI\AppData\Local\Temp\RtmpSSeXLZ\downloaded_packages’
Warning message:
package ‘ massFlowR’ is not available (for R version 3.6.3) 
  Error in library(massFlowR) : there is no package called ‘massFlowR’
Thank you for your attention.

**Comment by pshahnazari** [comment]
Hi again, I changed my version R to 4.0 but there is same error

**Comment by lauzikaite** [comment]
Yes, there is an error in your code. Please use my code directly as provided without modifications.
